//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme_database_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan_Resimleri
    {
        public int id { get; set; }
        public int ilan_id { get; set; }
        public string resim_url { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Ilanlar Ilanlar { get; set; }
    }
}
