//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme_database_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilanlar()
        {
            this.Favoriler = new HashSet<Favoriler>();
            this.Ilan_Resimleri = new HashSet<Ilan_Resimleri>();
            this.Mesajlar = new HashSet<Mesajlar>();
            this.Odemeler = new HashSet<Odemeler>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int id { get; set; }
        public string baslik { get; set; }
        public string aciklama { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public string ana_kategori { get; set; }
        public string alt_kategori { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string resim_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoriler> Favoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilan_Resimleri> Ilan_Resimleri { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
