//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme_database_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Is_Ilanları
    {
        public int id { get; set; }
        public string pozisyon { get; set; }
        public string sektör { get; set; }
        public string iş_tipi { get; set; }
        public Nullable<decimal> ücret { get; set; }
    }
}
