//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme_database_new.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bitirme_ProjesiEntities4 : DbContext
    {
        public Bitirme_ProjesiEntities4()
            : base("name=Bitirme_ProjesiEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler1> Adminler1 { get; set; }
        public virtual DbSet<Alısveris> Alısveris { get; set; }
        public virtual DbSet<Arama_Loglari> Arama_Loglari { get; set; }
        public virtual DbSet<Emlak> Emlak { get; set; }
        public virtual DbSet<Favoriler> Favoriler { get; set; }
        public virtual DbSet<Giyim_Taki> Giyim_Taki { get; set; }
        public virtual DbSet<Hizmetler_Egitim> Hizmetler_Egitim { get; set; }
        public virtual DbSet<Ilan_Resimleri> Ilan_Resimleri { get; set; }
        public virtual DbSet<Ilanlar> Ilanlar { get; set; }
        public virtual DbSet<Is_Ilanları> Is_Ilanları { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public virtual DbSet<Kullanici_Iletisim> Kullanici_Iletisim { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vasıta> Vasıta { get; set; }
        public virtual DbSet<Vasıta_Kategoriler> Vasıta_Kategoriler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
