//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme_database_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vasıta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vasıta()
        {
            this.Vasıta_Kategoriler = new HashSet<Vasıta_Kategoriler>();
        }
    
        public int id { get; set; }
        public string kategori_adi { get; set; }
        public string alt_kategori_adi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public Nullable<int> yil { get; set; }
        public Nullable<int> kilometre { get; set; }
        public string renk { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vasıta_Kategoriler> Vasıta_Kategoriler { get; set; }
    }
}
